[pytest]
pythonpath = .
testpaths = tests
markers =   order: define a ordem de execução dos testes
addopts =
    -v
    -s
    -n auto
    --html=report.html
    --self-contained-html
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --video=retain-on-failure
    --alluredir=allure-results
    --clean-alluredir
#Adicionar --headed no [addopts] se quiser abrir navegador, mas após rodar o comando {playwright install}, tal ação é necessário.
#-n auto ---> abre todos os navegadores de uma única vez (pip install pytest-xdist)
#--html=report.html ---> Gera um html com todas informações da execução (pip install pytest-html)
#--html=report.html --self-contained-html ---> O arquivo CSS que é gerado pelo "--html=report.html", o CSS pasará a ser salvo dentro do próprio html (pip install pytest-html)
#--screenshot=only-on-failure ---> Gera um screenshot apenas quando o teste falhar (pip install pytest-playwright)

; pip install pytest-playwright
; pip install pytest
; pip install allure-pytest
; pip install pytest-order
; pip install pytest-xdist
; pip install pytest-html
; pip freeze > requirements.txt
; playwright install