[pytest]
pythonpath = .
addopts = -v -s --alluredir=allure-results --clean-alluredir
testpaths = tests
markers =   order: define a ordem de execução dos testes

#Adicionar --headed no [addopts] se quiser abrir navegador, mas após rodar o comando {playwright install}, tal ação é necessário.